-- GloryTikTok production foundation
create extension if not exists pgcrypto;

create type public.app_role as enum ('user', 'admin', 'advertiser');
create type public.submission_status as enum ('pending', 'approved', 'rejected');
create type public.campaign_status as enum ('draft', 'active', 'paused', 'completed');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role public.app_role not null default 'user',
  balance integer not null default 0 check (balance >= 0),
  total_earned integer not null default 0 check (total_earned >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  creator text not null,
  description text not null default '',
  video_id text not null,
  points integer not null check (points > 0),
  duration_seconds integer not null check (duration_seconds between 5 and 3600),
  audience text not null default '',
  color text not null default '#5576d9',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  task_id bigint not null references public.tasks(id) on delete restrict,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status public.submission_status not null default 'pending',
  watched_seconds integer not null default 0 check (watched_seconds >= 0),
  liked boolean not null default false,
  subscribed boolean not null default false,
  secret_code_hash text,
  secret_code_verified_at timestamptz,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id),
  unique (task_id, user_id, submitted_at)
);

create table if not exists public.evidence (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.submissions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  storage_path text not null,
  kind text not null default 'screenshot',
  created_at timestamptz not null default now()
);

create table if not exists public.wallet_ledger (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  submission_id uuid unique references public.submissions(id) on delete restrict,
  amount integer not null check (amount > 0),
  reason text not null default 'task_reward',
  created_at timestamptz not null default now()
);

create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  advertiser_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  video_url text not null,
  target_participants integer not null check (target_participants > 0),
  points_per_task integer not null check (points_per_task > 0),
  budget_reserved integer not null check (budget_reserved >= 0),
  status public.campaign_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists submissions_user_idx on public.submissions(user_id, submitted_at desc);
create index if not exists submissions_status_idx on public.submissions(status, submitted_at desc);
create index if not exists evidence_submission_idx on public.evidence(submission_id);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, display_name) values (new.id, new.email, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1))) on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.approve_submission(p_submission_id uuid) returns void language plpgsql security definer set search_path = public as $$
declare s public.submissions%rowtype; t public.tasks%rowtype;
begin
  if not public.is_admin() then raise exception 'admin_required'; end if;
  select * into s from public.submissions where id = p_submission_id for update;
  if s.id is null or s.status <> 'pending' then raise exception 'submission_not_pending'; end if;
  select * into t from public.tasks where id = s.task_id;
  update public.submissions set status = 'approved', reviewed_at = now(), reviewed_by = auth.uid() where id = s.id;
  insert into public.wallet_ledger(user_id, submission_id, amount) values (s.user_id, s.id, t.points) on conflict (submission_id) do nothing;
  update public.profiles set balance = balance + t.points, total_earned = total_earned + t.points, updated_at = now() where id = s.user_id;
end; $$;

alter table public.profiles enable row level security;
alter table public.tasks enable row level security;
alter table public.submissions enable row level security;
alter table public.evidence enable row level security;
alter table public.wallet_ledger enable row level security;
alter table public.campaigns enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles for select using (id = auth.uid() or public.is_admin());
drop policy if exists tasks_select_active on public.tasks;
create policy tasks_select_active on public.tasks for select using (is_active = true or public.is_admin());
drop policy if exists submissions_select_own on public.submissions;
create policy submissions_select_own on public.submissions for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists submissions_insert_own on public.submissions;
create policy submissions_insert_own on public.submissions for insert with check (user_id = auth.uid());
drop policy if exists evidence_select_own on public.evidence;
create policy evidence_select_own on public.evidence for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists evidence_insert_own on public.evidence;
create policy evidence_insert_own on public.evidence for insert with check (user_id = auth.uid());
drop policy if exists ledger_select_own on public.wallet_ledger;
create policy ledger_select_own on public.wallet_ledger for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists campaigns_select_own on public.campaigns;
create policy campaigns_select_own on public.campaigns for select using (advertiser_id = auth.uid() or public.is_admin());
drop policy if exists campaigns_insert_own on public.campaigns;
create policy campaigns_insert_own on public.campaigns for insert with check (advertiser_id = auth.uid());

insert into public.tasks (id, title, creator, description, video_id, points, duration_seconds, audience, color) values
(1, 'Bilim: İnsanlar neden av eti yemez?', 'Tp Dossier', 'Videoyu keşfet, gerçek bir izleyici olarak katkını bırak.', 'J7nGqQJ8K4s', 100, 30, 'Yeni izleyiciler', '#ed7b42'),
(2, 'Algoritmanın arkasındaki gerçek', 'Kayıp Gerçekler', 'İzle, düşünceni bırak ve kanalı keşfet.', 'dQw4w9WgXcQ', 150, 30, 'Teknoloji meraklıları', '#5576d9'),
(3, 'Gündelik hayatın küçük bilimi', 'Merak Atölyesi', 'Manuel adımları tamamla; kanıt zincirini birlikte oluşturalım.', 'M7lc1UVf-VE', 80, 30, 'Bilim severler', '#8b64cf')
on conflict (id) do nothing;

insert into storage.buckets (id, name, public) values ('evidence', 'evidence', false) on conflict (id) do nothing;
drop policy if exists evidence_objects_insert on storage.objects;
create policy evidence_objects_insert on storage.objects for insert to authenticated with check (bucket_id = 'evidence' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists evidence_objects_select on storage.objects;
create policy evidence_objects_select on storage.objects for select to authenticated using (bucket_id = 'evidence' and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin()));
